### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by CharmingZhou** [PikaLabs/floyd#2]
src/http_conn.cc: 在成员函数‘bool pink::HttpConn::BuildRequestHeader()’中:
src/http_conn.cc:333:32: 错误：从类型‘int64_t* {aka long long int*}’到类型‘long int*’中的 static_cast 无效
         static_cast<long*>(&tmp));

**Comment by gaodq** [comment]
是mac平台吗？我们还没有做centos平台外的兼容性支持，在Linux上这些类型转换没有报错，可以做一下类型统一，提个pr :)

**Comment by CharmingZhou** [comment]
centos6.5

**Comment by CharmingZhou** [comment]
src/file_log.cc: 在成员函数‘bool floyd::Log::Recover()’中:
src/file_log.cc:83:36: 错误：‘sort’在此作用域中尚未声明
     sort(files.begin(), files.end());

**Comment by gaodq** [comment]
https://github.com/Qihoo360/pink/commit/6de9cab98207c323e499c9500864e61ae98ac52b 修复了src/http_conn.cc:333:32
src/file_log.cc:83:36: 错误，添加<algorithm>头文件
