### ISSUE TITLE
Use rocksdb::WriteBatch in RaftLog::TruncateSuffix

### ISSUE THREAD

**Issue by KernelMaker** [PikaLabs/floyd#26]
Use rocksdb::WriteBatch to remove all useless log in one batch, it better than calling rocksdb::Delete one by one

https://github.com/Qihoo360/floyd/blob/ca64b0c310aa5ea756268908aa3a72b002e8b17c/floyd/src/raft_log.cc#L123-L130

**Comment by baotiao** [comment]
can you fix this issue?  And can you suggest some other issue in how to use rocksdb in floyd @KernelMaker

**Comment by KernelMaker** [comment]
done
