### ISSUE TITLE
void Peer::RequestVoteRPC()实现中的一个小疑问

### ISSUE THREAD

**Issue by peacedog123** [PikaLabs/floyd#38]
在并行请求RequestVoteRPC的时候，目前的实现是只要有一个peer返回VOTE_DENIED, 就从candidate变为follower, 但是根据论文里面的实现，不是只要多数返回了VOTE_GRANTED就可以变为LEADER么？ 这里是不是返回VOTE_DENIED的时候简单记录下就好？谢谢

**Comment by gaodq** [comment]
收到了VOTE_DENIED就是说明有比这个节点更适合当leader的存在，所以它大概率不会称为leader，直接变为follower就好

**Comment by peacedog123** [comment]
部分情况下，VOTE_DENIED是peer选择了vote itself，这种情况下接收者感觉还是可以再等一等的；如果peer vote for others，这时按照你提到的到可以直接变成FOLLOWER。不知道这么理解对不对？

**Comment by gaodq** [comment]
如果是vote itself，那说明有多个节点变candidate了，论文里说这种情况下很有可能split vote，然后可以用随机election timeouts来减少这种情况，就是说一般情况下这种现象是非常少见的，并且raft的设计宗旨就是尽量简单易理解，对于这种少见状况那直接等超时重试就好。如果接受者等一等那到头来可能还是split vote，又要重新选，这样增加了实现复杂性

**Comment by peacedog123** [comment]
确实，我看到咱们这边没有实现 random election timeouts; 我再去了解下论文和实现，谢谢

**Comment by gaodq** [comment]
https://github.com/PikaLabs/floyd/blob/4113bef85e7fec2db743b7833c870574e106e239/floyd/src/floyd_options.cc#L110
在这有实现啊

**Comment by peacedog123** [comment]
啊，不好意思，没仔细看； 原以为是每次CheckLeader失败后都随机的，现在看来是一个固定值，但每个server不一样。

还一个问题哈，
int RaftLog::TruncateSuffix(uint64_t index)

这里Truncate log的时候是不是也应该加锁？

**Comment by gaodq** [comment]
在这
https://github.com/PikaLabs/floyd/blob/4113bef85e7fec2db743b7833c870574e106e239/floyd/src/floyd_impl.cc#L788

**Comment by peacedog123** [comment]
哦，我指的是

/*
   * mutex for last_log_index_
   */
  slash::Mutex lli_mutex_;

好像RaftLog里面涉及到rocksdb的读写的地方，都对这个mutex加锁了的

**Comment by gaodq** [comment]
看了下是有用这个锁，不过我觉得这个锁有点多余，大部分情况都用这个锁context_->global_mu保护了

**Comment by peacedog123** [comment]
哦，那这样看是可以考虑去除这个lli_mutex_了，原以为加入这个lli_mutex_是为了降低锁的粒度；看代码还发现有一点，很多涉及到context_的修改最后都会对应RaftMeta的相应操作，感觉可以考虑把RaftMeta直接作为context_的成员，对外部隐蔽
