### ISSUE TITLE
Read critical ?

### ISSUE THREAD

**Issue by demiaowu** [PikaLabs/floyd#39]
Hi, 在看 Floyd 代码时发现，Floyd 将 read 当做一条日志 Append 到 peers 解决脏读的问题，在 read log entry apply 之后，（1）通过 `context_->apply_cond.SignalAll();` 唤醒阻塞等待在 read 的 client 的，（2）然后 client 再 read rocksdb 中 k-v 返回给用户，但是感觉这样会有一 corner case  ？ 

上面标注的两步（1）（2）两步之间会存在一个**时间空隙**，尽管很小，但是在这段时候，如果针对同一个 key的一个新的 update command 被 apply，虽然没有 read 旧数据，但是 read 会读到更新的数据，

当然单 client 的情况下不会出现这种问题

**Comment by gaodq** [comment]
你说的情况会发生，但这是没问题的。就像下面这种情况，client1可能读到旧数据也可能读到新数据，单都是符合线性一致性的。

```
client1       |              read                |
client2               |     write    |
```

**Comment by demiaowu** [comment]
还有一个问题，Raft can execute a command multiple time，Floyd 是如何避免的 ？

**Comment by gaodq** [comment]
这个貌似是客户端语义的实现吧，floyd没有规定客户端实现，目前只支持kv的get set接口，所以命令都是幂等的，重复执行不会有坏的影响
