### ISSUE TITLE
floyd need add some extreme case to test it's safety

### ISSUE THREAD

**Issue by baotiao** [PikaLabs/floyd#7]
right now there is not enough case to test floyd's implementation of raft is safety, we should add some more extreme test case, or we should add some test tool like jepsen?

**Comment by baotiao** [comment]
The first case I want mention is test every node has different log entry, such as the example in raft's paper Figure 7

**Comment by leviathan0992** [comment]
@baotiao https://github.com/coreos/etcd/tree/master/raft/rafttest

**Comment by baotiao** [comment]
@Leviathan1995  these cases are too simple..

**Comment by baotiao** [comment]
floyd has pass jepsen linearizability.  We think jepsen's test case is strong engough

**Comment by baotiao** [comment]
we also add construct log tool to construct strange logs

**Comment by baotiao** [comment]
we have passed the jepsen test case.. so I can close this issue
