### ISSUE TITLE
About add a  simple example to test floyd

### ISSUE THREAD

**Issue by leviathan0992** [PikaLabs/floyd#8]
Maybe we can refer to the implementation of Raft by etcd.
site: https://github.com/coreos/etcd/tree/master/contrib/raftexample

**Comment by baotiao** [comment]
Yes, I am reading the interface of etcd's raft. And I havn't find a production ready raft implementation written by c++.
floyd want to be production read raft implementation

**Comment by leviathan0992** [comment]
etcd provides a simple REST API for operations, so it is very easy to implement some examples. Maybe HTTP is too heavy, but we can get some inspiration  for test floyd.

**Comment by baotiao** [comment]
etcd only provide a kv store by REST API. That's not what I wanted, floyd have a kv example, kv example have a server and a client. The same as etcd.
